version: '2'
services:
  neo4j:
    image: neo4j
    container_name: neo4j
    volumes:
      - ./databases/neo4j:/data
    environment:
      - NEO4J_AUTH=neo4j/123
    ports:
      - 7474:7474
      - 7687:7687
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./databases/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=123
    ports:
      - 27017:27017
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password #remove later when mysql client on node is updated
    volumes:
      - ./databases/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql
      - MYSQL_DATABASE=mydb
      - MYSQL_PASSWORD=123
    ports:
      - 3306:3306
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./databases/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432