version: '2'
services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password #remove later when mysql client on node is updated
    volumes:
      - ./databases/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql
      - MYSQL_DATABASE=mydb
      - MYSQL_PASSWORD=123
    ports:
      - 3306:3306