version: '2'
services:
  neo4j:
    image: neo4j
    container_name: neo4j
    volumes:
      - ./databases/neo4j:/data
    environment:
      - NEO4J_AUTH=neo4j/12345678
    ports:
      - 7474:7474
      - 7687:7687