#!/bin/bash
echo Name of you app
read folder
mkdir $folder
cd $folder
wget https://github.com/AlphaBril/clean-app/releases/download/v1.1/files.tar.gz &> /dev/null
tar -xvf files.tar.gz &> /dev/null
npx create-react-app app --template redux-typescript
cd app
npm install \
	@typescript-eslint/eslint-plugin \
	@typescript-eslint/parser \
	@types/jsonwebtoken \
	eslint-config-prettier \
	eslint-plugin-jest \
	eslint-plugin-react \
	eslint-plugin-react-hooks \
	eslint-plugin-prettier \
	eslint-plugin-import \
	prettier \
	antd \
	axios \
	i18next react-i18next i18next-browser-languagedetector \
	react-router-dom \
	jsonwebtoken socket.io-client
cp ../files/.eslintrc.js ./
cp ../files/tsconfig.json ./
cd src
cp ../../files/src/App.route.tsx ./
cp ../../files/src/App.test.tsx ./
cp ../../files/src/App.css ./
cp ../../files/src/App.tsx ./
cp ../../files/src/index.tsx ./
cp -R ../../files/src/components ./components
cp -R ../../files/src/ducks ./ducks
cp -R ../../files/src/hooks ./hooks
cp -R ../../files/src/store ./store
cp -R ../../files/src/utils ./utils
rm -rf app features
cd ..
npx prettier --write src/**/*.ts{,x}
cd ..
cp -R files/api ./
cd api
npm install \
	express \
	bcrypt \
	dotenv \
	jsonwebtoken \
	nodemailer \
	socket.io \
	dotenv \
	mysql \
	mongodb \
	pg \
	neo4j-driver

npm install --save-dev \
	@types/express \
	@types/jsonwebtoken \
	nodemon \
	eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser \
	prettier eslint-config-prettier eslint-plugin-prettier \
	typescript \
	ts-node
cd ..
rm -rf files files.tar.gz